[package]
name = "lib-inventory"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.*", features = ["dynamic_linking"] }
serde = "1.0.*"

[dependencies.lib-core]
path = "../lib-core"

[dependencies.lib-derive]
path = "../lib-derive"