[package]
name = "lib-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.*", features = ["dynamic_linking"] }

[dependencies.lib-core]
path = "../lib-core"

[dependencies.lib-inventory]
path = "../lib-inventory"
